import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        ink: "#13201c",
        muted: "#5d6b66",
        line: "#dde6e1",
        canvas: "#f7faf8",
        accent: "#176b57",
        "accent-soft": "#e4f3ec",
        warning: "#9a5b15",
        danger: "#9f2f2f",
        "app-bg": "rgb(var(--app-bg) / <alpha-value>)",
        "app-shell": "rgb(var(--app-shell) / <alpha-value>)",
        "app-surface": "rgb(var(--app-surface) / <alpha-value>)",
        "app-elevated": "rgb(var(--app-elevated) / <alpha-value>)",
        "app-border": "rgb(var(--app-border) / <alpha-value>)",
        "app-border-strong": "rgb(var(--app-border-strong) / <alpha-value>)",
        "app-text": "rgb(var(--app-text) / <alpha-value>)",
        "app-muted": "rgb(var(--app-muted) / <alpha-value>)",
        "app-subtle": "rgb(var(--app-subtle) / <alpha-value>)",
        "app-accent": "rgb(var(--app-accent) / <alpha-value>)",
        "app-accent-hover": "rgb(var(--app-accent-hover) / <alpha-value>)",
        "app-accent-soft": "rgb(var(--app-accent-soft) / <alpha-value>)",
        "app-success": "rgb(var(--app-success) / <alpha-value>)",
        "app-success-soft": "rgb(var(--app-success-soft) / <alpha-value>)",
        "app-warning": "rgb(var(--app-warning) / <alpha-value>)",
        "app-warning-soft": "rgb(var(--app-warning-soft) / <alpha-value>)",
        "app-danger": "rgb(var(--app-danger) / <alpha-value>)",
        "app-danger-soft": "rgb(var(--app-danger-soft) / <alpha-value>)",
        "app-danger-hover": "rgb(var(--app-danger-hover) / <alpha-value>)",
        "app-review": "rgb(var(--app-review) / <alpha-value>)",
        "app-review-soft": "rgb(var(--app-review-soft) / <alpha-value>)",
        "light-bg": "#f7f9fc",
        "light-shell": "#ffffff",
        "light-surface": "#ffffff",
        "light-elevated": "#eef3f8",
        "light-border": "#d7dee8",
        "light-border-strong": "#9aa8ba",
        "light-text": "#111827",
        "light-muted": "#4b5563",
        "light-subtle": "#6b7280",
        "light-accent": "#2563eb",
        "light-accent-hover": "#1d4ed8",
        "light-accent-soft": "#dbeafe",
        "light-success": "#15803d",
        "light-success-soft": "#dcfce7",
        "light-warning": "#b45309",
        "light-warning-soft": "#fef3c7",
        "light-danger": "#b91c1c",
        "light-danger-soft": "#fee2e2",
        "light-danger-hover": "#991b1b",
      },
      boxShadow: {
        soft: "0 18px 50px rgba(30, 49, 42, 0.08)",
        "app-soft": "var(--app-shadow)",
        "app-card": "var(--app-card-shadow)",
        "app-float": "var(--app-float-shadow)",
      },
      fontFamily: {
        sans: ["var(--font-geist-sans)", "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ["var(--font-geist-mono)", "ui-monospace", "monospace"],
      },
    },
  },
  plugins: [],
};

export default config;
